### ISSUE TITLE
Installation issue with R 3.4.3

### ISSUE THREAD

**Issue by npatibandla0214** [fishvice/dplyrOracle#2]
I am getting this error when I try to install the dplyrOracle, Can you please help

install_github("fishvice/dplyrOracle", force = TRUE)
Downloading GitHub repo fishvice/dplyrOracle@master
from URL https://api.github.com/repos/fishvice/dplyrOracle/zipball/master
Installing dplyrOracle
"C:/PROGRA~1/R/R-34~1.3PA/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/ch150319/AppData/Local/Temp/RtmpoR6B4t/devtools1e68d113d88/fishvice-dplyrOracle-abf36e3"  \
  --library="C:/Program Files/R/R-3.4.3patched/library" --install-tests 

* installing *source* package 'dplyrOracle' ...
** R
** preparing package for lazy loading
** help
Warning: C:/Users/ch150319/AppData/Local/Temp/RtmpoR6B4t/devtools1e68d113d88/fishvice-dplyrOracle-abf36e3/man/grapes-or-or-grapes.Rd: \name should not contain !, | or @
*** installing help indices
  converting help for package 'dplyrOracle'
    finding HTML links ... done
    build_query                             html  
    copy_env                                html  
    copy_to                                 html  
    db_drop_tables                          html  
    dplyrOracle                             html  
    grapes-or-or-grapes                     html  
    lahman                                  html  
    ora_sql                                 html  
    oracle_tables                           html  
    oracle_variables                        html  
    over                                    html  
    sql_translator                          html  
    sql_variant                             html  
    sql_vector_over                         html  
    src_oracle                              html  
    tbls                                    html  
    union_all                               html  
    union_all.tbl_oracle                    html  
    update                                  html  
    win_cumulative                          html  
    win_rank                                html  
    win_recycled                            html  
    win_single_arg                          html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'dplyrOracle':
object 'src_desc' not found whilst loading namespace 'dplyrOracle'
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'dplyrOracle':
object 'src_desc' not found whilst loading namespace 'dplyrOracle'
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Program Files/R/R-3.4.3patched/library/dplyrOracle'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by bthe** [comment]
dplyrOracle is now deprecated, you should use the developmental version of dbplyr (github.com/tidyverse/dbplyr)

**Comment by einarhjorleifsson** [comment]
time to delete this repo for good ??
